/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                surface: "#fff8f7",
                "error-container": "#ffdad6",
                "tertiary-fixed-dim": "#7bd1f8",
                "on-tertiary-fixed": "#001f2a",
                "on-secondary-container": "#616363",
                "primary-fixed-dim": "#ffb3ac",
                "primary-container": "#d32f2f",
                "on-primary-container": "#fff2f0",
                "on-tertiary-fixed-variant": "#004d65",
                "secondary-container": "#dfe0e0",
                "surface-dim": "#f1d3d0",
                "on-error-container": "#93000a",
                background: "#fff8f7",
                "on-secondary": "#ffffff",
                "tertiary-fixed": "#bee9ff",
                "surface-container-low": "#fff0ef",
                "secondary-fixed": "#e2e2e2",
                "on-tertiary": "#ffffff",
                "on-primary-fixed": "#410003",
                "outline-variant": "#e4beba",
                "on-background": "#271816",
                outline: "#8f6f6c",
                secondary: "#5d5f5f",
                "inverse-primary": "#ffb3ac",
                "surface-container-highest": "#f9dcd9",
                "on-surface": "#271816",
                "inverse-on-surface": "#ffedeb",
                "on-tertiary-container": "#e9f7ff",
                "on-secondary-fixed-variant": "#454747",
                "on-primary": "#ffffff",
                "surface-tint": "#ba1a20",
                "primary-fixed": "#ffdad6",
                "surface-container": "#ffe9e7",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#930010",
                "secondary-fixed-dim": "#c6c6c7",
                "on-secondary-fixed": "#1a1c1c",
                "on-surface-variant": "#5b403d",
                primary: "#af101a",
                "inverse-surface": "#3e2c2a",
                "surface-variant": "#f9dcd9",
                tertiary: "#005f7b",
                "surface-container-lowest": "#ffffff",
                error: "#ba1a1a",
                "surface-container-high": "#ffe2de",
                "surface-bright": "#fff8f7",
                "tertiary-container": "#00799c",
                "accent-success": "#2E7D32",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                base: "4px",
                gutter: "24px",
                margin: "32px",
                lg: "40px",
                md: "24px",
                sm: "16px",
                xs: "8px",
                xl: "64px",
            },
            fontFamily: {
                "label-bold": ["Inter", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                h3: ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                h1: ["Inter", "sans-serif"],
                h2: ["Inter", "sans-serif"],
                "label-sm": ["Inter", "sans-serif"],
            },
            fontSize: {
                "label-bold": ["14px", { lineHeight: "1.4", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
                h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                h1: [
                    "40px",
                    { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
                ],
                h2: [
                    "32px",
                    { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
                ],
                "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
            },
        },
    },
    plugins: [],
};
